apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: ecommerce
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Secure Ecommerce Platform</title>
        <style>
            body { background-color: #0d1117; color: #c9d1d9; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
            .card { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 40px; text-align: center; box-shadow: 0 8px 24px rgba(0,0,0,0.5); }
            h1 { color: #58a6ff; margin-bottom: 10px; }
            .status-box { background: #21262d; padding: 15px; border-radius: 6px; margin-top: 20px; border-left: 4px solid #238636; }
            .badge { color: #238636; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="card">
            <h1>Secure Ecommerce Platform</h1>
            <p>Welcome, Measchamrong. Your cluster is online.</p>
            <div class="status-box">
                <p>Status: <span class="badge">SYSTEMS OPERATIONAL</span></p>
                <small>Connected to Kubernetes (k3d)</small>
            </div>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: frontend-html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ecommerce
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
